### ISSUE TITLE
Guide link doesnt work

### ISSUE THREAD

**Issue by michaelrosstarr** [LukeIsHereToDevelop/opcommands#1]
Hi, the provided guide link doesnt work.

**Comment by michaelrosstarr** [comment]
Sorry, not guide, documentation link (this one: https://opcommands.lukedev.tk/)

**Comment by LukeIsHereToDevelop** [comment]
Hello! I wasn't working because I recently changed domain, here is the new one: https://opcommands.lukedev.site.
I will update the Documentation URL on the next version of OPCommands.
