### ISSUE TITLE
Message events not providing proper responses

### ISSUE THREAD

**Issue by MilleniumModsSources** [LukeIsHereToDevelop/opcommands#2]
So, I was doing some tests to log when a message is sent but noticed that the "_message_" parameter is not working.

Since I'm very bad with names in coding stuff, I'll provide an example.

With the messageCreate event using the event handler, I was trying to console log the message content of a message and it just didn't work. Also tried running the event on the main bot's file and it worked fine.

`module.exports = {
    name: "messageCreate",
    settings: {
        once: false
    },
    run: (message) => {
        console.log(message.content)
        }
}`

aside from that, the command handler seems to be working fine

discord.js v13.3.1
nodejs v16.10.0

**Comment by LukeIsHereToDevelop** [comment]
Hey! Thanks for creating an issue. By the way, the first parameter returns the bot client, not the message. The message parameter is the second one. Let me know if it works and thanks for using my command handler :)

**Comment by MilleniumModsSources** [comment]
Alright, that worked! Thanks. I'd recommend adding that clarification to the wiki, or even add a brief description for each option so it's more understandable

**Comment by LukeIsHereToDevelop** [comment]
> I'd recommend adding that clarification to the wiki, or even add a brief description for each option so it's more understandable
Done! I added a clarification on the [Setup](https://opcommands.lukedev.site/getting-started/setup) page.
